version: "3"
services:
  db:
    image: postgres:16.0
    container_name: project-db
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backups:/pg_backups

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: project-nginx
    image: nginx:1.23.3
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg_data:
  pg_backups:
