#!/bin/sh

PROJECT_NAME="project"

backend_precommit() {
    staged_backend_files=$(git diff --cached --name-only --diff-filter=ACM -- backend/)
    if [ -n "$staged_backend_files" ]; then
        cd backend

        docker exec "$PROJECT_NAME-backend" bash -c "rubocop"
        rubocop_result=$?
        if [ $rubocop_result -ne 0 ]; then
            echo "RuboCop failed for backend files. Aborting commit."
            exit 1
        fi

        echo "Running RSpec tests..."
        docker exec "$PROJECT_NAME-backend" bash -c "RAILS_ENV=test rspec"
        rspec_result=$?
        if [ $rspec_result -ne 0 ]; then
            echo "RSpec failed for backend files. Aborting commit."
            exit 1
        fi

        cd ..
    fi
}

backend_precommit

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=$(git hash-object -t tree /dev/null)
fi

allownonascii=$(git config --type=bool hooks.allownonascii)

exec 1>&2

if [ "$allownonascii" != "true" ] &&
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
    exit 1
fi

exec git diff-index --check --cached $against --
