#!/bin/sh

PROJECT_NAME="project"

backend_precommit() {
    staged_backend_files=$(git diff --cached --name-only --diff-filter=ACM -- backend/)
    if [ -n "$staged_backend_files" ]; then
        cd backend

        docker exec -t "$PROJECT_NAME-backend" sh -c "rubocop"
        rubocop_result=$?
        if [ $rubocop_result -ne 0 ]; then
            echo "RuboCop failed for backend files. Aborting commit."
            exit 1
        fi
    fi
}

backend_precommit
